<?php
defined('ABSPATH') or die("you do not have access to this page!");

/**
 * The condition key is used to check if all generated pages are available, the document can still be used if it is set to non-generated by complianz.
 */

$this->pages['us']['privacy-statement-children'] =
	array(
        'title' => __("Privacy Statement for Children (US)", 'complianz-gdpr'),
        'document_elements' => '',
        'condition' => array(
            'privacy-statement' => 'generated',
            'targets-children' => 'yes',
            'regions' => 'us',
        ),
        'public' => true,
);

$this->pages['uk']['privacy-statement-children'] =
	array(
        'title' => __("Privacy Statement for Children (UK)", 'complianz-gdpr'),
        'document_elements' => '',
        'condition' => array(
            'privacy-statement' => 'generated',
            'targets-children' => 'yes',
            'regions' => 'uk',
        ),
        'public' => true,

);

$this->pages['ca']['privacy-statement-children'] = array(
	    'title' => __("Privacy Statement for Children (CA)", 'complianz-gdpr'),
	    'document_elements' => '',
	    'condition' => array(
		    'privacy-statement' => 'generated',
		    'targets-children' => 'yes',
		    'regions' => 'ca',
	    ),
	    'public' => true,
);

$this->pages['au']['privacy-statement-children'] = array(
        'title' => __("Privacy Statement for Children (AU)", 'complianz-gdpr'),
        'document_elements' => '',
        'condition' => array(
            'privacy-statement' => 'generated',
            'targets-children' => 'yes',
            'regions' => 'au',
        ),
        'public' => true,
);

$this->pages['za']['privacy-statement-children'] =
	array(
		'title' => __("Privacy Statement for Children (ZA)", 'complianz-gdpr'),
		'document_elements' => '',
		'condition' => array(
			'privacy-statement' => 'generated',
			'targets-children' => 'yes',
			'regions' => 'za',
		),
		'public' => true,

	);

$this->pages['br']['privacy-statement-children'] =
	array(
		'title' => __("Privacy Statement for Children (BR)", 'complianz-gdpr'),
		'document_elements' => '',
		'condition' => array(
			'privacy-statement' => 'generated',
			'targets-children' => 'yes',
			'regions' => 'br',
		),
		'public' => true,

	);


$this->pages['all']['disclaimer'] =
	array(
        'title' => __("Disclaimer", 'complianz-gdpr'),
        'document_elements' => '',
        'condition' => array('disclaimer' => 'generated'),
        'public' => true,

);

$this->pages['eu']['processing'] = array(
        'title' => _x('Processing Agreement', 'Title on processing agreement page', 'complianz-gdpr'),
        'public' => false,
        'condition' => array(
	        'regions' => 'eu',
        ),
    );
$this->pages['us']['processing'] = array(
        'title' => _x('Processing Agreement', 'Title on processing agreement page', 'complianz-gdpr'),
        'public' => false,
        'condition' => array(
            'regions' => 'us',
        ),
    );
$this->pages['uk']['processing'] =  array(
        'title' => _x('Processing Agreement', 'Title on processing agreement page', 'complianz-gdpr'),
        'public' => false,
        'condition' => array(
            'regions' => 'uk',
        ),
    );
$this->pages['ca']['processing'] =  array(
	    'title' => _x('Processing Agreement', 'Title on processing agreement page', 'complianz-gdpr'),
	    'public' => false,
	    'condition' => array(
		    'regions' => 'ca',
	    ),
    );
$this->pages['au']['processing'] =  array(
        'title' => _x('Processing Agreement', 'Title on processing agreement page', 'complianz-gdpr'),
        'public' => false,
        'condition' => array(
            'regions' => 'au',
        ),
    );
$this->pages['za']['processing'] =  array(
	'title' => _x('Processing Agreement', 'Title on processing agreement page', 'complianz-gdpr'),
	'public' => false,
	'condition' => array(
		'regions' => 'za',
	),
);
$this->pages['br']['processing'] =  array(
	'title' => _x('Processing Agreement', 'Title on processing agreement page', 'complianz-gdpr'),
	'public' => false,
	'condition' => array(
		'regions' => 'br',
	),
);

$this->pages['eu']['dataleak'] =  array(
        'title' => __("Dataleak", 'complianz-gdpr'),
        'public' => false,
        'condition' => array(
	        'regions' => array('eu'),
        ),
    );
$this->pages['us']['dataleak'] =array(
        'title' => __("Dataleak", 'complianz-gdpr'),
        'public' => false,
        'condition' => array(
            'regions' => 'us',
        ),
    );
$this->pages['uk']['dataleak'] = array(
        'title' => __("Dataleak", 'complianz-gdpr'),
        'public' => false,
        'condition' => array(
            'regions' => 'uk',
        ),
    );

$this->pages['ca']['dataleak'] = array(
	    'title' => __("Dataleak", 'complianz-gdpr'),
	    'public' => false,
	    'condition' => array(
		    'regions' => 'ca',
	    ),
    );

$this->pages['au']['dataleak'] = array(
        'title' => __("Dataleak", 'complianz-gdpr'),
        'public' => false,
        'condition' => array(
            'regions' => 'au',
        ),
    );

$this->pages['za']['dataleak'] = array(
	'title' => __("Dataleak", 'complianz-gdpr'),
	'public' => false,
	'condition' => array(
		'regions' => 'za',
	),
);

$this->pages['br']['dataleak'] = array(
	'title' => __("Dataleak", 'complianz-gdpr'),
	'public' => false,
	'condition' => array(
		'regions' => 'br',
	),
);
