<?php
if ( function_exists( 'acf_add_local_field_group' ) ) :

    acf_add_local_field_group(
        array(
            'key'                   => 'group_layouts_configuration',
            'title'                 => 'Configuration - Layouts',
            'fields'                => array(
                array(
                    'key'                        => 'field_60ec5c6592be7',
                    'label'                      => '',
                    'name'                       => '',
                    'type'                       => 'message',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'hide_field'                 => '',
                    'hide_label'                 => 'all',
                    'hide_instructions'          => '',
                    'hide_required'              => '',
                    'acfe_permissions'           => '',
                    'acfe_save_meta'             => 0,
                    'instruction_placement'      => '',
                    'message'                    => '<p style="margin: 0;">Ajuster les paramètres de cette section.</p>',
                    'new_lines'                  => 'wpautop',
                    'esc_html'                   => 0,
                    'acfe_settings'              => '',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key'                        => 'field_section_id',
                    'label'                      => 'ID',
                    'name'                       => 'section_id',
                    'type'                       => 'text',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '49',
                        'class' => '',
                        'id'    => '',
                    ),
                    'hide_field'                 => '',
                    'hide_label'                 => '',
                    'hide_instructions'          => '',
                    'hide_required'              => '',
                    'instruction_placement'      => '',
                    'acfe_permissions'           => '',
                    'acfe_save_meta'             => 0,
                    'default_value'              => '',
                    'placeholder'                => '',
                    'prepend'                    => '#',
                    'append'                     => '',
                    'maxlength'                  => '',
                    'acfe_settings'              => '',
                    'acfe_validate'              => '',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key'                        => 'field_bg_color',
                    'label'                      => 'Couleur de fond',
                    'name'                       => 'bg_color',
                    'type'                       => 'pip_font_color',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '49',
                        'class' => '',
                        'id'    => '',
                    ),
                    'hide_field'                 => '',
                    'hide_label'                 => '',
                    'hide_instructions'          => '',
                    'hide_required'              => '',
                    'instruction_placement'      => '',
                    'acfe_permissions'           => '',
                    'acfe_save_meta'             => 0,
                    'field_type'                 => 'select',
                    'multiple'                   => 0,
                    'ui'                         => 0,
                    'pip_default_value'          => '',
                    'class_output'               => 'background',
                    'show_add_to_editor'         => 1,
                    'acfe_settings'              => '',
                    'acfe_validate'              => '',
                    'acfe_field_group_condition' => 0,
                    'choices'                    => array(),
                    'placeholder'                => '',
                    'return_format'              => 'value',
                    'allow_null'                 => true,
                    'other_choice'               => 0,
                    'allow_custom'               => 0,
                    'ajax'                       => false,
                ),
                array(
                    'key'                        => 'field_60ec5c3792be4',
                    'label'                      => '<i class="far fa-desktop-alt"></i>',
                    'name'                       => '',
                    'type'                       => 'tab',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'hide_field'                 => '',
                    'hide_label'                 => '',
                    'hide_instructions'          => '',
                    'hide_required'              => '',
                    'instruction_placement'      => '',
                    'acfe_permissions'           => '',
                    'placement'                  => 'top',
                    'endpoint'                   => 0,
                    'no_preference'              => 0,
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key'                        => 'field_vertical_spacing',
                    'label'                      => 'Espacement ↕',
                    'name'                       => 'vertical_space',
                    'type'                       => 'button_group',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '49',
                        'class' => '',
                        'id'    => '',
                    ),
                    'hide_field'                 => '',
                    'hide_label'                 => '',
                    'hide_instructions'          => '',
                    'hide_required'              => '',
                    'instruction_placement'      => '',
                    'acfe_permissions'           => '',
                    'acfe_save_meta'             => 0,
                    'choices'                    => array(
                        'py-0'  => 'Aucun',
                        'py-4'  => 'XS',
                        'py-6'  => 'S',
                        'py-8'  => 'M',
                        'py-16' => 'L',
                        'py-20' => 'XL',
                        'py-32' => '2XL',
                        'py-48' => '3XL',
                    ),
                    'allow_null'                 => 0,
                    'default_value'              => 'py-16',
                    'layout'                     => 'horizontal',
                    'return_format'              => 'value',
                    'acfe_settings'              => '',
                    'acfe_validate'              => '',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key'                        => 'field_60ec5c4c92be5',
                    'label'                      => '<i class="far fa-tablet-alt"></i>',
                    'name'                       => '',
                    'type'                       => 'tab',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'hide_field'                 => '',
                    'hide_label'                 => '',
                    'hide_instructions'          => '',
                    'hide_required'              => '',
                    'acfe_permissions'           => '',
                    'instruction_placement'      => '',
                    'placement'                  => 'top',
                    'endpoint'                   => 0,
                    'no_preference'              => 0,
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key'                        => 'field_60ec599d4977b',
                    'label'                      => 'Espacement ↕',
                    'name'                       => 'vertical_space_tablet',
                    'type'                       => 'button_group',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '49',
                        'class' => '',
                        'id'    => '',
                    ),
                    'hide_field'                 => '',
                    'hide_label'                 => '',
                    'hide_instructions'          => '',
                    'hide_required'              => '',
                    'instruction_placement'      => '',
                    'acfe_permissions'           => '',
                    'acfe_save_meta'             => 0,
                    'choices'                    => array(
                        'py-0'  => 'Aucun',
                        'py-4'  => 'XS',
                        'py-6'  => 'S',
                        'py-8'  => 'M',
                        'py-16' => 'L',
                        'py-20' => 'XL',
                        'py-32' => '2XL',
                        'py-48' => '3XL',
                    ),
                    'allow_null'                 => 0,
                    'default_value'              => 'py-8',
                    'layout'                     => 'horizontal',
                    'return_format'              => 'value',
                    'acfe_settings'              => '',
                    'acfe_validate'              => '',
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key'                        => 'field_60ec5c5792be6',
                    'label'                      => '<i class="far fa-mobile-alt"></i>',
                    'name'                       => '',
                    'type'                       => 'tab',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'hide_field'                 => '',
                    'hide_label'                 => '',
                    'hide_instructions'          => '',
                    'hide_required'              => '',
                    'acfe_permissions'           => '',
                    'instruction_placement'      => '',
                    'placement'                  => 'top',
                    'endpoint'                   => 0,
                    'no_preference'              => 0,
                    'acfe_field_group_condition' => 0,
                ),
                array(
                    'key'                        => 'field_60ec55a365b1b',
                    'label'                      => 'Espacement ↕',
                    'name'                       => 'vertical_space_mobile',
                    'type'                       => 'button_group',
                    'instructions'               => '',
                    'required'                   => 0,
                    'conditional_logic'          => 0,
                    'wrapper'                    => array(
                        'width' => '49',
                        'class' => '',
                        'id'    => '',
                    ),
                    'hide_field'                 => '',
                    'hide_label'                 => '',
                    'hide_instructions'          => '',
                    'hide_required'              => '',
                    'instruction_placement'      => '',
                    'acfe_permissions'           => '',
                    'acfe_save_meta'             => 0,
                    'choices'                    => array(
                        'py-0'  => 'Aucun',
                        'py-4'  => 'XS',
                        'py-6'  => 'S',
                        'py-8'  => 'M',
                        'py-16' => 'L',
                        'py-20' => 'XL',
                        'py-32' => '2XL',
                        'py-48' => '3XL',
                    ),
                    'allow_null'                 => 0,
                    'default_value'              => 'py-6',
                    'layout'                     => 'horizontal',
                    'return_format'              => 'value',
                    'acfe_settings'              => '',
                    'acfe_validate'              => '',
                    'acfe_field_group_condition' => 0,
                ),
            ),
            'location'              => array(
                array(
                    array(
                        'param'    => 'post_type',
                        'operator' => '==',
                        'value'    => 'all',
                    ),
                ),
            ),
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'tooltip',
            'hide_on_screen'        => '',
            'active'                => false,
            'description'           => '',
            'acfe_autosync'         => array(
                0 => 'json',
            ),
            'acfe_form'             => 1,
            'acfe_display_title'    => '',
            'acfe_permissions'      => '',
            'acfe_meta'             => '',
            'acfe_note'             => '',
            'acfe_categories'       => array(
                'pilopress' => 'Pilo\'Press',
            ),
        )
    );

endif;
